export interface RequiredConcept {
  name: string;
  description: string;
}

export interface Rubric {
  topic: string;
  required_concepts: RequiredConcept[];
}

// Concepts are fixed by us, not generated by the LLM per request.
// This keeps grading anchored to a stable rubric instead of letting
// the same model that grades also invent what it grades against.
export const RUBRICS: Record<string, Rubric> = {
  "Binary Search": {
    topic: "Binary Search",
    required_concepts: [
      {
        name: "Sorted input requirement",
        description:
          "Binary search requires the searchable data to be ordered according to the search criterion.",
      },
      {
        name: "Middle element comparison",
        description:
          "The algorithm compares the target with the middle element of the current search range.",
      },
      {
        name: "Search-space reduction",
        description:
          "Based on the comparison, approximately half of the remaining search space is discarded.",
      },
      {
        name: "Repeated process",
        description:
          "The process continues on the remaining half until the target is found or the search range becomes empty.",
      },
      {
        name: "Time complexity",
        description: "Binary search has logarithmic O(log n) search complexity.",
      },
    ],
  },
  Recursion: {
    topic: "Recursion",
    required_concepts: [
      {
        name: "Self-reference",
        description: "A recursive function solves a problem by calling itself directly or indirectly.",
      },
      {
        name: "Base case",
        description: "A base case stops further recursive calls.",
      },
      {
        name: "Problem reduction",
        description: "Each recursive call should work on a smaller or simpler version of the problem.",
      },
      {
        name: "Call stack",
        description: "Recursive calls create stack frames that return in reverse order.",
      },
      {
        name: "Termination risk",
        description:
          "Without a reachable base case or sufficient progress, recursion may continue until stack overflow.",
      },
    ],
  },
  "SQL JOINs": {
    topic: "SQL JOINs",
    required_concepts: [
      {
        name: "Combining tables",
        description: "A JOIN combines related rows from two or more tables.",
      },
      {
        name: "Join condition",
        description: "Rows are matched using a condition, commonly related key columns.",
      },
      {
        name: "INNER JOIN",
        description: "INNER JOIN returns rows where the join condition matches on both sides.",
      },
      {
        name: "LEFT JOIN",
        description:
          "LEFT JOIN keeps every row from the left table and uses NULL values when the right side has no match.",
      },
      {
        name: "Multiplicity",
        description: "A join can produce multiple result rows when more than one row satisfies the relationship.",
      },
    ],
  },
};

export function getRubric(topic: string): Rubric {
  const rubric = RUBRICS[topic];
  if (!rubric) {
    const known = Object.keys(RUBRICS).join(", ");
    throw new Error(`No rubric for topic "${topic}". Known topics: ${known}`);
  }
  return rubric;
}
